# Generated by Django 4.2 on 2023-05-02 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=254)),
                ('streetName', models.CharField(max_length=254, null=True)),
                ('houseNumber', models.CharField(max_length=254, null=True)),
                ('city', models.CharField(max_length=254, null=True)),
                ('postalCode', models.CharField(max_length=254, null=True)),
                ('password', models.CharField(max_length=254)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(choices=[('S', '9"'), ('M', '12"'), ('L', '16"')], max_length=1)),
                ('topping', models.ManyToManyField(to='pizzafront.topping')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerName', models.CharField(max_length=254)),
                ('offerPrice', models.DecimalField(decimal_places=2, max_digits=254)),
                ('pizza', models.ManyToManyField(to='pizzafront.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.ManyToManyField(to='pizzafront.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ManyToManyField(to='pizzafront.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartSum', models.DecimalField(decimal_places=2, max_digits=254)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ManyToManyField(to='pizzafront.offer')),
                ('pizza', models.ManyToManyField(to='pizzafront.pizza')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pizzafront.user')),
            ],
        ),
    ]
