# Generated by Django 4.2 on 2023-05-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzafront', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cartSum',
            new_name='cart_sum',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='offerName',
            new_name='offer_name',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='offerPrice',
            new_name='offer_price',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='houseNumber',
            new_name='house_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='streetName',
            new_name='street_name',
        ),
    ]
