# Generated by Django 4.2 on 2023-05-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzafront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartofferquantity',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_quantities', to='pizzafront.cart'),
        ),
    ]
