# Generated by Django 4.2 on 2023-05-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzafront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_offer_quantity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_offer', to='pizzafront.cartofferquantity')),
                ('pizzas', models.ManyToManyField(to='pizzafront.pizza')),
            ],
        ),
    ]
