# Generated by Django 4.2 on 2023-05-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzafront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpizza',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
