# Generated by Django 4.2 on 2023-05-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzafront', '0002_rename_cartsum_cart_cart_sum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'Spicy'), ('V', 'Vegan')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_image',
            field=models.ImageField(default='img.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_image',
            field=models.ImageField(default='img.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pizzafront.pizzatype'),
        ),
    ]
