# Generated by Django 4.2 on 2023-05-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzafront', '0002_alter_cartofferquantity_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='offer_quantity',
            field=models.ManyToManyField(related_name='carts_with_offer_quantity', through='pizzafront.CartOfferQuantity', to='pizzafront.offer'),
        ),
    ]
