# Generated by Django 4.2 on 2023-05-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzafront', '0002_cartoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
