# Generated by Django 4.2 on 2023-05-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzafront', '0003_pizzatype_offer_offer_image_pizza_pizza_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
